https://plantuml.com/salt

@startuml
' After assignment *Creator*
salt
{^"Create a new Monster"
Name        | "Mycoolak"
Element     | ^FIRE^
Max Energy  | "12"
Max Health  | "10"
[CREATE!]
}
@enduml

@startuml
' After assignment *Resistances*
salt
{^"Create a new Monster"
Name        | "Mycoolak"
Element     | ^FIRE^
Max Energy  | "12"
Max Health  | "10"
Resistances | [] FIRE
.           | [] ICE
.           | [] ACID
.           | [] POISON
[CREATE!]
}
@enduml

@startuml
' After assignment *Attacks*
salt
{^"Create a new Monster"
Name        | "Mycoolak"
Element     | ^FIRE^
Max Energy  | "12"
Max Health  | "10"
Resistances | [] FIRE
.           | [] ICE
.           | [] ACID
.           | [] POISON
Attacks     | Name | "Shard" | Damage | "3 " | Cost | "2 " | [<&x>]
.           | Name | "Spit " | Damage | "2 " | Cost | "2 " | [<&x>]
.           | Name | "Slit " | Damage | "1 " | Cost | "1 " | [<&x>]
.           | [<&plus>]
[CREATE!]
}
@enduml
